[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["gui"]
description = "Minimal UI library based on GTK+."
documentation = "https://antoyo.github.io/mg/mg/"
license = "MIT"
name = "mg"
repository = "https://github.com/antoyo/mg"
version = "0.0.5-pre"

[dependencies]
error-chain = "^0.10.0"
futures = "^0.1.14"
futures-glib = "^0.1.0"
gdk = "^0.5.2"
glib = "^0.1.2"
gtk = "^0.1.2"
log = "^0.3"
mg-settings = "^0.2.0"
pango = "^0.1.3"
relm = "^0.10.0"
relm-attributes = "^0.10.0"
relm-derive = "^0.10.0"

[dev-dependencies]
libxdo = "^0.4.1"
mg-settings-macros = "^0.2.0"
pretty_env_logger = "^0.1.0"

[features]
default = ["gtk/v3_22"]
nightly = []
