[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["gui"]
description = "Minimal UI library based on GTK+."
documentation = "https://antoyo.github.io/mg/mg/"
license = "MIT"
name = "mg"
repository = "https://github.com/antoyo/mg"
version = "0.0.5-pre"

[dependencies]
gdk = "^0.5.2"
gdk-sys = "^0.3.3"
glib = "^0.1.2"
glib-sys = "^0.3.3"
gobject-sys = "^0.3.3"
gtk = "^0.1.2"
gtk-sys = "^0.3.3"
libc = "^0.2"
log = "^0.3"
mg-settings = "^0.1.0"
pango-sys = "^0.3.3"
relm = { git = "https://github.com/antoyo/relm", branch = "feature/futures-glib" } #"^0.9.0"
relm-attributes = { git = "https://github.com/antoyo/relm", branch = "feature/futures-glib" } #"^0.9.0"
relm-derive = { git = "https://github.com/antoyo/relm", branch = "feature/futures-glib" } #"^0.9.0"

[dev-dependencies]
libxdo = "^0.4.1"
mg-settings-macros = "^0.0.2"

[features]
nightly = []

[replace]
"gdk-sys:0.3.3" = { git = "https://github.com/antoyo/sys" }

[replace."futures:0.1.13"]
branch = "spawn-trait"
git = "https://github.com/alexcrichton/futures-rs"
