[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["gui"]
description = "Minimal UI library based on GTK+."
documentation = "https://antoyo.github.io/mg/mg/"
license = "MIT"
name = "mg"
repository = "https://github.com/antoyo/mg"
version = "0.0.5-pre"

[dependencies]
libc = "^0.2"
log = "^0.3"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk"
version = "0.5.0"

[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"
version = "0.1.0"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.mg-settings]
git = "https://github.com/antoyo/mg-settings"
version = "^0.0.5-pre"

[dependencies.pango-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dev-dependencies]
libxdo = "^0.4.1"

[dev-dependencies.mg-settings-macros]
git = "https://github.com/antoyo/mg-settings"
version = "^0.0.1"

[features]
nightly = []
