[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["gui"]
description = "Minimal UI library based on GTK+."
documentation = "https://antoyo.github.io/mg/mg/"
license = "MIT"
name = "mg"
repository = "https://github.com/antoyo/mg"
version = "0.6.0"

[dependencies]
futures = "^0.1.14"
futures-glib = "^0.3.0"
gdk = "^0.7.0"
glib = "^0.4.0"
gtk = "^0.3.0"
log = "^0.3"
mg-settings = "^0.4.0"
pango = "^0.3.0"
relm = "^0.11.0"
relm-attributes = "^0.11.0"
relm-derive = "^0.11.0"

[dev-dependencies]
libxdo = "^0.4.1"
mg-settings-macros = "^0.4.0"
pretty_env_logger = "^0.1.0"

[features]
default = ["gtk/v3_22"]
nightly = []
