[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["gui"]
description = "Minimal UI library based on GTK+."
documentation = "https://antoyo.github.io/mg/mg/"
license = "MIT"
name = "mg"
repository = "https://github.com/antoyo/mg"
version = "0.0.5-pre"

[dependencies]
gdk = "^0.5.2"
glib = "^0.1.2"
gtk = "^0.1.2"
libc = "^0.2"
log = "^0.3"
mg-settings = "^0.1.0"
pango = "^0.1.3"

[dependencies.relm]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.relm-attributes]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.relm-derive]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dev-dependencies]
libxdo = "^0.4.1"
mg-settings-macros = "^0.1.0"

[features]
default = ["gtk/v3_22"]
nightly = []

[replace."futures:0.1.13"]
branch = "spawn-trait"
git = "https://github.com/alexcrichton/futures-rs"
